#!/bin/sh
set -e

case "${1-}" in
    configure)
        if [ -f /usr/share/debconf/confmodule ]; then
            # shellcheck disable=SC1091
            . /usr/share/debconf/confmodule

            db_version 2.0

            db_input medium supermon-ng/configure-apache || true
            db_input medium supermon-ng/disable-default-sites || true

            if [ -f /etc/apache2/sites-available/supermon-ng.conf ]; then
                db_input high supermon-ng/refresh-apache-site || true
            fi

            db_go || true
            db_stop || true
        fi
        ;;
esac

exit 0
