#!/bin/sh

printf "CPU: "

if [ -r /sys/class/thermal/thermal_zone0/temp ]; then
    CTEMP_MILLI=$(cat /sys/class/thermal/thermal_zone0/temp)
else
    printf "<span style=\"color: red;\">ERROR: Cannot read temperature</span>\n"
    exit 1
fi

if ! expr "$CTEMP_MILLI" : '^[0-9][0-9]*$' > /dev/null; then
    printf "<span style=\"color: red;\">ERROR: Invalid temperature value '%s'</span>\n" "$CTEMP_MILLI"
    exit 1
fi

CTEMP=$((CTEMP_MILLI / 1000))

FTEMP=$(printf "%s * %s / 5 + 32\n" 9 "$CTEMP" | bc)

if [ "$FTEMP" -le 120 ]; then
    printf "<span style=\"background-color: palegreen;\">"
elif [ "$FTEMP" -le 150 ]; then
    printf "<span style=\"background-color: yellow;\">"
else
    printf "<span style=\"font-weight: bold; color: yellow; background-color: red;\">"
fi

printf " %s°F, %s°C </span>  @ %s \n" \
    "$FTEMP" \
    "$CTEMP" \
    "$(date +%H:%M)"

exit 0